on:
  push:
    branches:
      - main

name: Release

jobs:
  npm:
    runs-on: ubuntu-latest
    steps:
      - id: auth
        uses: jnwng/github-app-installation-token-action@v2
        with:
          appId: ${{ secrets.GITHUB_APP_ID }}
          installationId: ${{ secrets.GITHUB_APP_INSTALLATION_ID }}
          privateKey: ${{ secrets.ORG_PRIVATE_KEY }}
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: main
      - uses: actions/setup-node@v2
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm run install
      - run: npm run build
      - run: npm run semantic-release
        env:
          GH_TOKEN: ${{ steps.auth.outputs.token }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
